//ACTION TYPES
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const REQUEST_POSTS_SUCCESS = 'REQUEST_POSTS_SUCCESS';
export const REQUEST_POSTS_ERROR = 'REQUEST_POSTS_ERROR';
export const START_POLLING = 'START_POLLING';
export const STOP_POLLING = 'STOP_POLLING';